/* Close Community — Service Worker (offline support) */
/* Auto-generated by scripts/build-products.mjs — do not hand-edit ASSETS */
const CACHE = 'cc-b078f950';
const ASSETS = [
  './',
  'index.html',
  'styles.css',
  'site.js',
  'play.html',
  'minesweeper.html',
  'random.html',
  'archive.html',
  'favicon.ico',
  'favicon-32.png',
  'favicon-192.png',
  'logos/web/TYPO_LOGO.webp',
  'logos/web/TYPO_LOGO.png',
  'logos/web/LETTERS_LOGO_TRANSPARENT.webp',
  'logos/web/LETTERS_LOGO_TRANSPARENT.png',
  'product/gatun-cammo-hats.html',
  'product/angel-down-tee.html',
  'product/font-tee.html',
  'product/stars-tee.html',
  'product/basic-tee-oversized.html',
  'product/cc-socks.html',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/BLACK_GOLD_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/BLACK_GOLD_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/OFFWHITE_ORANGE_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/OFFWHITE_ORANGE_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/PINK_ORANGE_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/PINK_ORANGE_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/BLACK_GOLD_BACK_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/BLACK_GOLD_BACK_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/BLACK_GOLD_SIDE_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/BLACK_GOLD_SIDE_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/OFFWHITE_ORANGE_BACK_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/OFFWHITE_ORANGE_BACK_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/OFFWHITE_ORANGE_SIDE_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/OFFWHITE_ORANGE_SIDE_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/PINK_ORANGE_BACK_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/PINK_ORANGE_BACK_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/PINK_ORANGE_SIDE_MOCKUP.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_HATS/web/PINK_ORANGE_SIDE_MOCKUP.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/ANGEL_DOWN_TEE/web/CUTOUT.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/ANGEL_DOWN_TEE/web/CUTOUT.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/FONT_TEE/web/FRONT_SIDE_FONT_TEE.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/FONT_TEE/web/FRONT_SIDE_FONT_TEE.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/FONT_TEE/web/BACK_SIDE_FONT_TEE.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/FONT_TEE/web/BACK_SIDE_FONT_TEE.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/STARSTEE.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/STARSTEE.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/BLACK_STARSTEE.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/BLACK_STARSTEE.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/STARS_TEE_P_W.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/STARS_TEE_P_W.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/STARRS_TEE_P_B.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/STARS_TEE/web/STARRS_TEE_P_B.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/BASIC_TEE_OVERSIZED/web/CUTOUT.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/BASIC_TEE_OVERSIZED/web/CUTOUT.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_SOCKS/web/BLACK.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_SOCKS/web/BLACK.png',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_SOCKS/web/WHITE.webp',
  'TRANSPARENT_MOCKUPS/CAPSULA%2001/CC_SOCKS/web/WHITE.png',
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(ASSETS))
  );
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', e => {
  e.respondWith(
    caches.match(e.request).then(cached => {
      // Cache-first for same-origin assets, network-first for fonts/CDN
      if (cached && new URL(e.request.url).origin === location.origin) {
        return cached;
      }
      return fetch(e.request).then(res => {
        // Cache same-origin successful responses
        if (res.ok && new URL(e.request.url).origin === location.origin) {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return res;
      }).catch(() => cached || new Response('Offline', {status: 503}));
    })
  );
});
